config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets

  namespace :admin do
    resources :trains do
      resources :wagons
      resources :tickets
      post :add_route
      post :del_route
    end
    resources :railway_stations do
      patch :update_time_and_position, on: :member
    end
    resources :routes do
      resources :railway_stations
      post :add_station
      post :del_station
    end
    resources :users, except: :new do
      resources :tickets
    end
    resources :wagons
    resources :tickets
  end

  post :search, to: 'search#search'
  get 'search/index'
  get 'welcome/index'
  root 'welcome#index'
end

app/models/route.rb
class Route < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validate :stations_count

  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains
  has_many :tickets

  before_validation :set_title

  scope :station, -> { where(type: 'RailwayStation') }
  scope :ordered, -> {order(:number)}

  def self.search_in_route_train(start_station_id, end_station_id)
    found_routes = []
    found_train = []

    self.all.each do |route|
      if route.railway_stations.find_by(id: start_station_id) && route.railway_stations.find_by(id: end_station_id)
        found_routes << route
      end
    end

    found_routes.each do |found_route|
      found_route.trains.each do |train|
        found_train << train
      end
    end
    return found_train
  end

  private

  def set_title
    self.title = "#{railway_stations.first.title}-#{railway_stations.last.title}"
  end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, "Маршрут должен содержать минимум 2 станции")
    end
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController

  def index
    @routes = Route.all
  end

  def show
    @route = Route.find(params[:id])
    @trains = Train.all
  end

  def new
    @route = Route.new
  end

  def edit
    @route = Route.find(params[:id])
    @railway_stations = RailwayStation.all - @route.railway_stations
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to [:admin, @route]
    else
      render 'new'
    end
  end

  def update
    @route = Route.find(params[:id])
    @railway_stations = @route.railway_stations

      redirect_to admin_routes_path
  end

  def destroy
    @route = Route.find(params[:id])
    @route.destroy

    redirect_to admin_routes_path
  end

  def add_station
    @station = RailwayStation.find(params[:railway_station])
    @route = Route.find(params[:route_id])
    @route.railway_stations.push(@station)
    redirect_to edit_admin_route_path(@route)
  end

  def del_station
    @station = RailwayStation.find(params[:railway_station])
    @route = Route.find(params[:route_id])
    @route.railway_stations.delete(@station)
    redirect_to edit_admin_route_path(@route)
  end

  private

  def route_params
    params.require(:route).permit(:title, :text, railway_station_ids: [], station_number: [])
  end
end

app/helpers/routes_helper.rb
module RoutesHelper

  def route_full_name route
    return if route.railway_stations_routes.map(&:position).include? nil
    r = route.railway_stations_routes.sort_by { |k| k.position }
    r.first.railway_station.title + ' - ' + r.last.railway_station.title
  end
end

app/views/admin/routes/_form.html.erb
<%= form_for [:admin, route], html: { style: "display: #{hidden ? 'none' : 'block'}"} do |form| %>
  <%= render 'common/errors', resource: route %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :route_title %>
  </p>

  <div class="field">
    <%= form.label :railway_station_ids, 'Текущая станция' %>
    <%= form.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true}  %>
  </div>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit "#{ route.new_record? ? 'Создать' : 'Изменить' }" %>
  </p>

<% end %>

app/views/admin/routes/edit.html.erb
<h1>Изменение маршрута</h1>

<%= render 'form', route: @route, hidden: true %>

<p>
  <strong>Содержит станции:</strong>
  <%- @route.railway_stations.each do |st| %>
    <p>
      <%  %>
      <%= link_to 'Удалить станцию', admin_route_del_station_path(@route, railway_station: st), method: :post %>
      <%= st.title %>
  <%- end %>
</p>
<p>
  <strong>Добавить станции:</strong>
  <%- @railway_stations.each do |st| %>
    <p>
      <%= link_to 'Добавить станцию', admin_route_add_station_path(@route, railway_station: st), method: :post %>
      <%= st.title %>
  <%- end %>
</p>


<%= link_to 'Назад', admin_routes_path %>

app/views/admin/routes/index.html.erb
<h1>Маршруты</h1>
<%= link_to 'На главную', root_path %>

<table class="table table-striped">
  <tr>
    <th>Наименование</th>
    <th>Дополнительные сведения</th>
    <th colspan="3"></th>
  </tr>

  <% @routes.each do |route| %>
    <tr>
      <td>
        <div id="route_title_<%= route.id %>">
          <%= link_to route_full_name(route), [:admin, route] %>
        </div>
        <%= render 'form', route: route, hidden: true %>
      </td>
      <td><%= route.text %></td>
      <td><%= link_to 'Изменить', '', class: 'edit_route', data: { route_id: route.id } %></td>
      <td><%= link_to 'Удалить', [:admin, route],
              method: :delete,
              data: { confirm: 'Вы уверены?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Новый маршрут', new_admin_route_path %>

app/views/admin/routes/new.html.erb
<h1>Новый маршрут</h1>

<%= render 'form', route: @route, hidden: false %>

<%= link_to 'Назад', admin_routes_path %>

app/views/admin/routes/show.html.erb
<p> Маршрут </p>
<p>
  <strong>Наименование:</strong>
  <%= route_full_name(@route) %>
</p>

<p>
  <strong>Дополнительные сведения:</strong>
  <%= @route.text %>
</p>

<p>
  <strong>Поезда:</strong>
  <%- @route.trains.each do |train| %>
  <%= full_name(train) %>
  <%- end %>
</p>

<p>
  <strong>Станции:</strong>
  <% if @route.railway_stations.empty? %>
  Список пуст
    <% else %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th width="100px">Название</th>
            <th>Позиция</th>
            <th>Прибытие</th>
            <th>Отправление</th>
            <th></th>
          </tr>
        </thead>
      <tbody>
        <% @route.railway_stations.ordered.each do |station| %>
          <tr>
            <td><%= station.title %></td>
            <%= form_tag update_time_and_position_admin_railway_station_path(station), method: :patch do %>
              <td>
                <%= number_field_tag :position, station.position_in(@route) %>
              </td>
              <td>
                <%= time_field_tag :arrival_time, station.arrival_time(@route) %>
              </td>
              <td>
                <%= time_field_tag :departure_time, station.departure_time(@route) %>
              </td>
              <td>
                <%= hidden_field_tag :route_id, @route.id %>
                <%= submit_tag "Изменить" %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</p>

<%= link_to 'Изменить', edit_admin_route_path(@route) %>
<%= link_to 'Назад', admin_routes_path %>