config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets

  namespace :admin do
    resources :trains do
      resources :wagons
      resources :tickets
      post :add_route
      post :del_route
    end
    resources :railway_stations do
      patch :update_time_and_position, on: :member
    end
    resources :routes do
      resources :railway_stations
      post :add_station
      post :del_station
    end
    resources :users, except: :new do
      resources :tickets
    end
    resources :wagons
    resources :tickets
  end

  post :search, to: 'search#search'
  get 'search/index'
  get 'welcome/index'
  root 'welcome#index'
end

app/models/train.rb
class Train < ApplicationRecord
  validates :number, presence: true, uniqueness: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :wagons

end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
    @routes = Route.all
  end

  def create
    @train = Train.new(train_params)
    respond_to do |format|
      if @train.save
        format.html { redirect_to [:admin, @train], notice: 'Train was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to admin_trains_path, notice: 'Train was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to admin_trains_path, notice: 'Train was successfully destroyed.' }
    end
  end

  def add_route
    @route = Route.find(params[:route])
    @train = Train.find(params[:train_id])
    @train.route = @route
    @train.save
    redirect_to edit_train_path(@train)
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id, :route_id, :sort_by_tail)
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
  def full_name(train)
    "<#{train.number.to_s}> #{train.route.railway_stations.first.title} - #{train.route.railway_stations.last.title}"
  end
end

app/views/admin/trains/_form.html.erb
<%= form_for [:admin, train], html: { style: "display: #{hidden ? 'none' : 'block'}"} do |form| %>
  <%= render 'common/errors',  resource: train %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :train_number %>
  </div>

  <div class="field">
    <%= form.label :current_station %>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :route_id, 'Маршрут' %>
    <%= form.collection_select :route_id, Route.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.label :sort_by_tail, 'Нумерация вагонов с хвоста поезда' %>
    <%= form.check_box :sort_by_tail %>
  </div>

  <div class="actions">
    <%= form.submit "#{ train.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td>
    <div id="train_number_<%= train.id %>">
      <%= link_to full_name(train), [:admin, train] %>
    </div>
    <%= render 'form', train: train, hidden: true %>
  </td>
  <td><%= link_to train.route.railway_stations.size, admin_railway_stations_path %></td>
  <td><%= link_to train.wagons.size, admin_train_path(train) %></td>
  <td><%= link_to train.tickets.size, tickets_path %></td>
  <td><%= link_to 'Создать билет', new_admin_ticket_path(train: train) %></td>
  <td><%= link_to 'Изменить', '', class: 'edit_train', data: { train_id: train.id } %></td>
  <td><%= link_to 'Удалить', [:admin, train], method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1>Изменение поезда</h1>

<%= render 'form', train: @train, hidden: false %>

<p>
  <strong>Маршрут:</strong>
  <% if @train.route.present? %>
    <%= @train.route.title %>
  <% else %>
    Не указано
  <% end %>
</p>

<%= link_to 'Просмотр', [:admin, @train] %> |
<%= link_to 'Назад', admin_trains_path %>

app/views/admin/trains/index.html.erb
<h1>Поезда</h1>
<%= link_to 'На главную', root_path %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Номер</th>
      <th>Станции</th>
      <th>Вагоны</th>
      <th>Билеты</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'Новый поезд', new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1>Новый поезд</h1>

<%= render 'form', train: @train, hidden: false %>

<%= link_to 'Назад', admin_trains_path %>

app/views/admin/trains/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong>Номер поезда:</strong>
  <%= @train.number %>
</h1>
<p>
  <strong>Находится на станции:</strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
    Не указано
  <% end %>
</p>
<p>
  <strong>Маршрут:</strong>
  <% if @train.route.present? %>
    <%= route_full_name @train.route %>
  <% else %>
    Маршрут не назначен
  <% end %>
</p>
<p>
  <strong>Количество вагонов:</strong>
  <ul>
    <li>Плацкартных: <%= @train.wagons.select { |wagon| wagon.type == 'EconomyWagon' }.size %></li>
    <li>Купейных:    <%= @train.wagons.select { |wagon| wagon.type == 'CoupeWagon' }.size %></li>
    <li>СВ:          <%= @train.wagons.select { |wagon| wagon.type == 'SvWagon' }.size %></li>
    <li>Сидячих:     <%= @train.wagons.select { |wagon| wagon.type == 'SedentaryWagon' }.size %></li>
    <li> Вагоны:
      <% @train.wagons.each do |wagon| %>
        <%= link_to wagon.number, admin_wagon_path(wagon) %>
      <% end %>
    </li>

    <li>
      <% if @train.sort_by_tail %>
        Нумерация вагонов с хвоста поезда
      <% else %>
        Нумерация вагонов с головы поезда
      <% end %>
    </li>
  </ul>
</p>
<p>
  <strong>Добавить вагон:</strong>
</p>
  <p><%= select_tag :wagon, options_for_select(Wagon::WAGON_TYPES, Wagon::WAGON_TYPES.first), id: 'select_wagon_type' %></p>
  <p><%= link_to 'Добавить', new_admin_train_wagon_path(@train, type: ''),  class: 'btn btn-primary', id: 'wagon_type_button' %></p>
</p>
<p>
  <strong>Билеты:</strong>
  <ul>
    <% @train.tickets.each do |ticket| %>
      <li>
        <b>№<%= ticket.number %></b> _
        Пользователь: <%= ticket.user&.full_name %>;
        Вагон: <%= ticket.wagon&.number %>;
        Станция: <%= ticket.start_station&.title %>
      </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Изменить', edit_admin_train_path(@train) %> |
<%= link_to 'Назад', admin_trains_path %>