config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets

  namespace :admin do
    resources :trains do
      resources :wagons
      resources :tickets
      post :add_route
      post :del_route
    end
    resources :railway_stations do
      patch :update_time_and_position, on: :member
    end
    resources :routes do
      resources :railway_stations
      post :add_station
      post :del_station
    end
    resources :users, except: :new do
      resources :tickets
    end
    resources :wagons
    resources :tickets
  end

  post :search, to: 'search#search'
  get 'search/index'
  get 'welcome/index'
  root 'welcome#index'
end

app/models/wagon.rb
class Wagon < ApplicationRecord
  validates :number, presence: true
  belongs_to :train
  has_many :tickets

  WAGON_TYPES = [['Плацкарт', 'EconomyWagon'], ['Купе', 'CoupeWagon'], ['Сидячий', 'SedentaryWagon'], ['СВ', 'SvWagon']]
  scope :economy,   -> { where(type: 'EconomyWagon') }
  scope :coupe,     -> { where(type: 'CoupeWagon') }
  scope :sedentary, -> { where(type: 'SedentaryWagon') }
  scope :sv,        -> { where(type: 'SvWagon') }
  scope :sort_desc, -> { order('number DESC') }
  scope :sort_asc,  -> { order('number') }

  def type_name
    case self.type
      when "EconomyWagon"   then "Плацкарт"
      when "CoupeWagon"     then "Купе"
      when "SvWagon"        then "СВ"
      when "SedentaryWagon" then "Сидячий"
      else "Тип не назначен"
    end
  end

  def self.seats_type(type)
    case type
      when :top_seats         then "Верхние места"
      when :bottom_seats      then "Нижние места"
      when :side_bottom_seats then "Боковые нижние места"
      when :side_top_seats    then "Боковые верхние места"
      when :sedentary_seats   then "Сидячие места"
      else "Тип не назначен"
    end
  end

  def set_wagon_number
    train.wagons == [] ? 1 : train.wagons.maximum(:number) + 1
  end

  def seats_count_for_wagon_type
    seat_types.map do |seat_type|
      self.class.where(type: type, train_id: train_id).map(&seat_type).sum
    end.sum
  end
end

app/controllers/admin/wagons_controller.rb
class Admin::WagonsController < Admin::BaseController
  before_action :set_wagon, only: [:show, :edit, :update, :destroy]
  before_action :set_train, only: [:new, :create, :edit, :update]

  def index
    @wagons = Wagon.all
  end

  def show
  end

  def new
    @wagon = params[:type].constantize.new(wagon_params)
  end

  def edit
    @trains = Train.all
  end

  def create
    @wagon = params[:type].constantize.new(wagon_params)
    @wagon.number = @wagon.set_wagon_number
    @wagon.seats_count_for_wagon_type
    respond_to do |format|
      if @wagon.save
        format.html { redirect_to admin_train_path(@train), notice: 'Wagon was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @wagon.update(wagon_params)
        format.html { redirect_to @wagon, notice: 'Wagon was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @wagon.destroy
    respond_to do |format|
      format.html { redirect_to wagons_url, notice: 'Wagon was successfully destroyed.' }
    end
  end

  private

  def set_train
    @train = Train.find params[:train_id]
  end

  def set_wagon
    @wagon = Wagon.find(params[:id])
  end

  def wagon_params
    params.permit(:number, :train_id, :bottom_seats, :top_seats, :side_bottom_seats, :side_top_seats, :sedentary_seats, :type)
  end
end

app/helpers/wagons_helper.rb
module WagonsHelper
end

app/views/admin/wagons/_form.html.erb
<%= form_with(url: admin_wagons_path(train_id: @train.id, type: @wagon.class)) do |f| %>
  <%= render 'common/errors', resource: @wagon %>

  <p>Добавление <%= @wagon.type_name %> вагона к поезду №<%= @train.number %></p>

  <% @wagon.seat_types.each do |seat| %>
    <div class="field">
      <%= f.label seat, Wagon.seats_type(seat) %>
      <%= f.number_field seat %>
    </div>
  <% end %>

  <% f.hidden_field :train_id, value: @train.id %>

  <div class="actions">
    <%= f.submit "#{ @wagon.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/admin/wagons/_wagon.html.erb
<tr>
  <td><%= link_to wagon.number, admin_wagon_path(wagon) %></td>
  <td><%= wagon.train.number if wagon.train %></td>
  <td><%= wagon.type = wagon.type_name%></td>
  <td><ul>
    <%- wagon.seat_types.each do |type| %>
      <li>
      <%= Wagon.seats_type(type) %>
      <%= ': ' + wagon.send(type).to_s %>
    </li>
    <% end %>
  </ul></td>
  <td><%= link_to 'Изменить', edit_admin_wagon_path(wagon, train_id: wagon.train&.id) if wagon.train %></td>
  <td><%= link_to 'Удалить', admin_wagon_path(wagon), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/admin/wagons/edit.html.erb
<h1>Изменение вагона</h1>

<%= render 'form', wagon: @wagon %>

<p>
  <strong>Поезд:</strong>
  <% if @wagon.train.present? %>
    <%= @wagon.train.number %>
  <% else %>
    Не указано
  <% end %>
</p>

<%= link_to 'Просмотр', admin_wagon_path(@wagon) %> |
<%= link_to 'Назад', admin_wagons_path %>

app/views/admin/wagons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Вагоны</h1>
<%= link_to 'На главную', root_path %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Номер</th>
      <th>Поезд</th>
      <th>Тип</th>
      <th>Места</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'admin/wagons/wagon', collection: @wagons %>
  </tbody>
</table>

<br>

app/views/admin/wagons/new.html.erb
<h1>Новый вагон</h1>

    <%= render 'form', wagon: @wagon %>

<%= link_to 'Назад', admin_wagons_path %>

app/views/admin/wagons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Номер вагона:</strong>
  <%= @wagon.number %>
</p>
<p>
  <strong>Поезд:</strong>
  <% if @wagon.train.present? %>
    <%= @wagon.train.number %>
  <% else %>
    Не указано
  <% end %>
</p>
<p>
  <strong>Тип:</strong>
  <% if @wagon.type.present? %>
    <%= @wagon.type %>
  <% else %>
    Тип не назначен
  <% end %>
</p>
<p>
  <strong>Всего мест <%= @wagon.type_name %> в поезде <%= @wagon.train.number %>:</strong>
  <%= @wagon.seats_count_for_wagon_type %>
</p>
<p>
  <strong>Вагон <%= @wagon.number %></strong>

<ul>
   <li>ID <%= @wagon.id.to_s %></li>
   <li>Тип <%= @wagon.type %></li>
   <li>Боковых верхних:  <%= @wagon.side_top_seats %> мест</li>
   <li>Верхних:          <%= @wagon.bottom_seats %> мест</li>
   <li>Нижних:           <%= @wagon.bottom_seats %> мест</li>
   <li>Боковых нижних:   <%= @wagon.side_top_seats %> мест</li>
   <li>Сидячих:          <%= @wagon.sedentary_seats %> мест</li>
</ul>

<%= link_to 'Изменить', edit_admin_train_wagon_path(train_id: @wagon.train.id, id: @wagon.id) %> |
<%= link_to 'Назад', admin_train_path(@wagon.train)%>