config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets

  namespace :admin do
    resources :trains do
      resources :wagons
      resources :tickets
      post :add_route
      post :del_route
    end
    resources :railway_stations do
      patch :update_time_and_position, on: :member
    end
    resources :routes do
      resources :railway_stations
      post :add_station
      post :del_station
    end
    resources :users, except: :new do
      resources :tickets
    end
    resources :wagons
    resources :tickets
  end

  post :search, to: 'search#search'
  get 'search/index'
  get 'welcome/index'
  root 'welcome#index'
end

app/views/layouts/_footer.html.erb
<p>
  <strong>(c) 2018 Nariel Katarios. Обучение.</strong>
</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutu - Администратор</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'Tutu', root_path, class: 'navbar-brand' %>
    <div class="navbar-collapse collapse navbar-responsive-collapse navbar-inverse">
      <ul class="nav navbar-nav" class="text-light bg-dark">
        <% if user_signed_in? %>
          <li><%= link_to 'Выйти', destroy_user_session_path, method: :delete  %></li>
          <li><%= link_to 'Список станций', admin_railway_stations_path %></li>
          <li><%= link_to 'Список поездов', admin_trains_path %></li>
          <li><%= link_to 'Список маршрутов', admin_routes_path %></li>
          <li><%= link_to 'Список билетов', tickets_path %></li>
          <li><%= link_to 'Список пользователей', admin_users_path %></li>
          <li><%= link_to 'Список вагонов', admin_wagons_path %></li>
          <li><%= link_to 'Поиск билетов', search_index_path %></li>
        <% else %>
          <li><%= link_to 'Войти', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div><!--/row-->

  <footer>
    <p>&copy; Company 2018</p>
  </footer>

</div> <!-- /container -->

</body>
</html>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tutu" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9] -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Tutu', root_path, class: 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-inverse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to 'Купленные билеты', tickets_path %></li>
              <li><%= link_to 'Выйти', destroy_user_session_path, method: :delete  %></li>
            <% else %>
              <li><%= link_to 'Войти', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <% if user_signed_in? %>
      <p>Аккаунт: <%= current_user&.email %></p>
      <p>Привет, <%= current_user&.full_name %>!</p>
    <% end %>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <br>
          <br>
          <br>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>